import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : value === 'ja' || value === 'jp' ? 'ja' : 'zh';

/**
 * Map a report language to a UI-chrome language. The Web UI shell only ships
 * zh/en strings, so Japanese reports fall back to the English UI chrome.
 */
export const reportLanguageToUiLanguage = (value?: string | null): 'zh' | 'en' => {
  const normalized = normalizeReportLanguage(value);
  return normalized === 'zh' ? 'zh' : 'en';
};

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
  },
  ja: {
    keyInsights: '主要なインサイト',
    noAnalysisSummary: '分析結論はまだありません',
    actionAdvice: 'アクション提案',
    noAdvice: '提案はまだありません',
    trendPrediction: 'トレンド予測',
    noPrediction: '予測はまだありません',
    marketSentiment: '市場心理',
    strategyPoints: '戦略ポイント',
    sniperLevels: '売買ポイント',
    idealBuy: '理想的な買い場',
    secondaryBuy: '次善の買い場',
    stopLoss: '損切り価格',
    takeProfit: '利確目標',
    noValue: '—',
    newsFeed: 'ニュースフィード',
    relatedNews: '関連ニュース',
    refresh: '更新',
    retry: '再試行',
    dismiss: '閉じる',
    details: '詳細を見る',
    loadingNews: 'ニュースを読み込み中...',
    noNews: '関連ニュースはありません',
    noNewsDescription: '後ほど更新して最新ニュースを確認してください。',
    openLink: '開く',
    transparency: '透明性',
    traceability: 'データ追跡',
    rawResult: '元の分析結果',
    analysisSnapshot: '分析スナップショット',
    copy: 'コピー',
    copied: 'コピーしました',
    recordId: 'レコード ID',
    fullReport: '完全な分析レポート',
    loadingReport: 'レポートを読み込み中...',
    loadReportFailed: 'レポートの読み込みに失敗しました',
    copyMarkdownSource: 'Markdown ソースをコピー',
    copyPlainText: 'プレーンテキストをコピー',
    analysisModel: '分析モデル',
    fearGreedIndex: '恐怖・強欲指数',
    boardLinkage: 'セクター連動',
    relatedBoards: '関連セクター',
    leadingBoard: '上昇主導',
    laggingBoard: '下落主導',
    neutralBoard: '中立',
    reanalyze: '再分析',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
